import './main/mainIndex.js'
import './animations/menuPlace.js'
import './animations/contentMain.js'
import './animations/cardsActivities.js'
import './javascript/menuResponsive.js'
import './javascript/buttonMobile.js'
import './javascript/Darkmode.js'
import './javascript/btnSubMenu.js'
console.log("prin main");
